#!/usr/bin/python3
def raise_exception_msg(message=""):[^1^][1]
    raise NameError(message)
